package com.ztraqto.openxross.core.command;

import net.dv8tion.jda.api.Permission;
import net.dv8tion.jda.api.entities.Member;
import net.dv8tion.jda.api.entities.Message;
import net.dv8tion.jda.api.interactions.commands.OptionType;
import net.dv8tion.jda.api.interactions.commands.build.OptionData;
import com.ztraqto.openxross.api.command.CommandContext;
import com.ztraqto.openxross.api.command.SlashCommand;
import com.ztraqto.openxross.service.EditorSessionService;
import com.ztraqto.openxross.api.settings.SettingScope;

import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.util.Locale;
import java.util.Map;
import java.util.stream.Collectors;

public final class ApplySettingsCommand extends SlashCommand {

    private static final int MAX_APPLY_FILE_BYTES = 64 * 1024;

    public ApplySettingsCommand() {
        super("apply", "Apply a setting code generated by Xross Editor");
        addOption(new OptionData(OptionType.STRING, "code", "Xross setting code", false)
                .setMinLength(16)
                .setMaxLength(6000));
        addOption(new OptionData(OptionType.ATTACHMENT, "file", "Xross Editor apply file", false));
        setHelp("/apply code:<code> or file:<apply-file>", "Applies a signed Xross Editor setting code or file. The same Editor session can be applied repeatedly for 30 minutes.");
    }

    @Override
    public void execute(CommandContext context) {
        EditorSessionService editor = context.getEngine().getServiceManager().getService(EditorSessionService.class);
        if (editor == null || !editor.isEnabled()) {
            context.replyErrorTr("cmd.apply.error.not-configured");
            return;
        }

        String code = context.getOptionAsString("code");
        Message.Attachment file = context.getOption("file") == null
                ? null
                : context.getOption("file").getAsAttachment();
        if ((code == null || code.isBlank()) == (file == null)) {
            context.replyErrorTr("cmd.apply.error.one-source");
            return;
        }

        if (file == null) {
            applyCodeAndReply(context, editor, code);
            return;
        }
        if (file.getSize() > MAX_APPLY_FILE_BYTES || !isApplyFile(file.getFileName())) {
            context.replyErrorTr("cmd.apply.error.invalid-file");
            return;
        }

        context.getEvent().deferReply(true).queue(hook -> file.getProxy().download().whenComplete((input, failure) -> {
            if (failure != null) {
                hook.editOriginal("❌ " + context.tr("cmd.apply.error.download-file")).queue();
                return;
            }
            try (input) {
                hook.editOriginal(applyCode(context, editor, readCode(input))).queue();
            } catch (Exception exception) {
                hook.editOriginal("❌ " + errorMessage(exception)).queue();
            }
        }));
    }

    private static void applyCodeAndReply(CommandContext context, EditorSessionService editor, String code) {
        try {
            context.reply(applyCode(context, editor, code), true);
        } catch (Exception exception) {
            context.replyError(errorMessage(exception));
        }
    }

    private static String applyCode(CommandContext context, EditorSessionService editor, String code) {
        long guildId = context.getEvent().getGuild() == null ? 0L : context.getEvent().getGuild().getIdLong();
        long userId = context.getEvent().getUser().getIdLong();
        SettingScope scope = editor.getApplyScope(code, guildId, userId);
        if (scope == SettingScope.GUILD && (context.getEvent().getGuild() == null || !canManageServer(context.getEvent().getMember()))) {
            throw new IllegalArgumentException(context.tr("cmd.apply.error.manage-server"));
        }
        Map<String, com.fasterxml.jackson.databind.JsonNode> changed = editor.apply(
                guildId,
                userId,
                code
        );
        if (changed.isEmpty()) {
            return context.tr("cmd.apply.response.no-changes");
        }
        String keys = changed.keySet().stream().sorted().collect(Collectors.joining("\n- ", "- ", ""));
        return context.tr("cmd.apply.response.success", keys);
    }

    private static String readCode(InputStream input) throws IOException {
        byte[] bytes = input.readNBytes(MAX_APPLY_FILE_BYTES + 1);
        if (bytes.length > MAX_APPLY_FILE_BYTES) {
            throw new IllegalArgumentException("Apply file is too large.");
        }
        return new String(bytes, StandardCharsets.UTF_8).trim();
    }

    private static boolean isApplyFile(String fileName) {
        String normalized = fileName == null ? "" : fileName.toLowerCase(Locale.ROOT);
        return normalized.endsWith(".xrossa") || normalized.endsWith(".xe4a") || normalized.endsWith(".txt");
    }

    private static String errorMessage(Exception exception) {
        return exception.getMessage() == null || exception.getMessage().isBlank()
                ? "Could not apply the Xross Editor settings."
                : exception.getMessage();
    }

    private static boolean canManageServer(Member member) {
        return member != null && member.hasPermission(Permission.MANAGE_SERVER);
    }
}
